package com.ongo.domain.video.entity

import java.time.LocalDateTime

data class VideoSubtitle(
    val id: Long? = null,
    val videoId: Long,
    val language: String = "ko",
    val format: String = "srt",
    val content: String,
    val isAutoGenerated: Boolean = true,
    val createdAt: LocalDateTime? = null,
    val updatedAt: LocalDateTime? = null,
)
