package com.ongo.infrastructure.persistence.jooq

import com.ongo.domain.video.VideoSubtitleRepository
import com.ongo.domain.video.entity.VideoSubtitle
import com.ongo.infrastructure.persistence.jooq.Fields.CONTENT
import com.ongo.infrastructure.persistence.jooq.Fields.CREATED_AT
import com.ongo.infrastructure.persistence.jooq.Fields.FORMAT
import com.ongo.infrastructure.persistence.jooq.Fields.ID
import com.ongo.infrastructure.persistence.jooq.Fields.IS_AUTO_GENERATED
import com.ongo.infrastructure.persistence.jooq.Fields.LANGUAGE
import com.ongo.infrastructure.persistence.jooq.Fields.UPDATED_AT
import com.ongo.infrastructure.persistence.jooq.Fields.VIDEO_ID
import com.ongo.infrastructure.persistence.jooq.Tables.VIDEO_SUBTITLES
import org.jooq.DSLContext
import org.jooq.Record
import org.springframework.stereotype.Repository

@Repository
class VideoSubtitleJooqRepository(
    private val dsl: DSLContext,
) : VideoSubtitleRepository {

    override fun save(subtitle: VideoSubtitle): VideoSubtitle {
        val id = dsl.insertInto(VIDEO_SUBTITLES)
            .set(VIDEO_ID, subtitle.videoId)
            .set(LANGUAGE, subtitle.language)
            .set(FORMAT, subtitle.format)
            .set(CONTENT, subtitle.content)
            .set(IS_AUTO_GENERATED, subtitle.isAutoGenerated)
            .onConflict(VIDEO_ID, LANGUAGE)
            .doUpdate()
            .set(FORMAT, subtitle.format)
            .set(CONTENT, subtitle.content)
            .set(IS_AUTO_GENERATED, subtitle.isAutoGenerated)
            .returningResult(ID)
            .fetchOne()!!
            .get(ID)

        return findById(id)!!
    }

    override fun findByVideoId(videoId: Long): List<VideoSubtitle> =
        dsl.select()
            .from(VIDEO_SUBTITLES)
            .where(VIDEO_ID.eq(videoId))
            .orderBy(CREATED_AT.asc())
            .fetch()
            .map { it.toVideoSubtitle() }

    override fun findByVideoIdAndLanguage(videoId: Long, language: String): VideoSubtitle? =
        dsl.select()
            .from(VIDEO_SUBTITLES)
            .where(VIDEO_ID.eq(videoId))
            .and(LANGUAGE.eq(language))
            .fetchOne()
            ?.toVideoSubtitle()

    override fun update(subtitle: VideoSubtitle): VideoSubtitle {
        dsl.update(VIDEO_SUBTITLES)
            .set(CONTENT, subtitle.content)
            .set(FORMAT, subtitle.format)
            .set(IS_AUTO_GENERATED, subtitle.isAutoGenerated)
            .where(ID.eq(subtitle.id))
            .execute()

        return findById(subtitle.id!!)!!
    }

    override fun delete(id: Long) {
        dsl.deleteFrom(VIDEO_SUBTITLES)
            .where(ID.eq(id))
            .execute()
    }

    private fun findById(id: Long): VideoSubtitle? =
        dsl.select()
            .from(VIDEO_SUBTITLES)
            .where(ID.eq(id))
            .fetchOne()
            ?.toVideoSubtitle()

    private fun Record.toVideoSubtitle(): VideoSubtitle = VideoSubtitle(
        id = get(ID),
        videoId = get(VIDEO_ID),
        language = get(LANGUAGE) ?: "ko",
        format = get(FORMAT) ?: "srt",
        content = get(CONTENT) ?: "",
        isAutoGenerated = get(IS_AUTO_GENERATED) ?: true,
        createdAt = localDateTime(CREATED_AT),
        updatedAt = localDateTime(UPDATED_AT),
    )
}
