package com.ongo.application.video

import com.ongo.application.credit.CreditService
import com.ongo.common.exception.ForbiddenException
import com.ongo.common.exception.NotFoundException
import com.ongo.domain.video.VideoRepository
import com.ongo.domain.video.VideoSubtitleRepository
import com.ongo.domain.video.entity.VideoSubtitle
import org.springframework.context.ApplicationEventPublisher
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional

@Service
@Transactional(readOnly = true)
class CaptionUseCase(
    private val videoRepository: VideoRepository,
    private val subtitleRepository: VideoSubtitleRepository,
    private val creditService: CreditService,
    private val eventPublisher: ApplicationEventPublisher,
) {

    @Transactional
    fun generateCaption(userId: Long, videoId: Long, language: String = "ko") {
        val video = videoRepository.findById(videoId)
            ?: throw NotFoundException("영상", videoId)
        if (video.userId != userId) throw ForbiddenException("해당 영상에 대한 접근 권한이 없습니다")

        val fileUrl = video.fileUrl
            ?: throw IllegalStateException("파일 업로드가 완료되지 않은 영상입니다")

        // Deduct AI credits for caption generation
        creditService.validateAndDeduct(userId, 5, "CAPTION_GENERATION")

        eventPublisher.publishEvent(
            CaptionGenerationEvent(
                videoId = videoId,
                userId = userId,
                fileUrl = fileUrl,
                language = language,
            )
        )
    }

    fun getCaptions(userId: Long, videoId: Long): List<VideoSubtitle> {
        val video = videoRepository.findById(videoId)
            ?: throw NotFoundException("영상", videoId)
        if (video.userId != userId) throw ForbiddenException("해당 영상에 대한 접근 권한이 없습니다")

        return subtitleRepository.findByVideoId(videoId)
    }

    @Transactional
    fun updateCaption(userId: Long, videoId: Long, language: String, content: String): VideoSubtitle {
        val video = videoRepository.findById(videoId)
            ?: throw NotFoundException("영상", videoId)
        if (video.userId != userId) throw ForbiddenException("해당 영상에 대한 접근 권한이 없습니다")

        val subtitle = subtitleRepository.findByVideoIdAndLanguage(videoId, language)
            ?: throw NotFoundException("자막", videoId)

        return subtitleRepository.update(
            subtitle.copy(
                content = content,
                isAutoGenerated = false,
            )
        )
    }

    @Transactional
    fun deleteCaption(userId: Long, videoId: Long, subtitleId: Long) {
        val video = videoRepository.findById(videoId)
            ?: throw NotFoundException("영상", videoId)
        if (video.userId != userId) throw ForbiddenException("해당 영상에 대한 접근 권한이 없습니다")

        subtitleRepository.delete(subtitleId)
    }
}
