import type { Platform } from './channel'

export type MediaType = 'VIDEO' | 'IMAGE'

export type UploadStatus =
  | 'DRAFT'
  | 'UPLOADING'
  | 'PROCESSING'
  | 'REVIEW'
  | 'PUBLISHED'
  | 'FAILED'
  | 'REJECTED'

export type Visibility = 'PUBLIC' | 'PRIVATE' | 'UNLISTED'

export interface ContentImage {
  id: number
  imageUrl: string
  displayOrder: number
  width?: number
  height?: number
}

export interface Video {
  id: number
  userId: number
  title: string
  description: string | null
  tags: string[]
  category: string | null
  mediaType: MediaType
  fileUrl: string
  thumbnailUrl: string | null
  thumbnailCandidates: string[]
  autoThumbnails: string[]
  selectedThumbnailIndex: number
  duration: number | null
  fileSize: number | null
  resolution: string | null
  status: UploadStatus
  visibility: Visibility
  createdAt: string
  updatedAt: string
  uploads: VideoUpload[]
  contentImages?: ContentImage[]
}

export interface VideoUpload {
  id: number
  videoId: number
  platform: Platform
  status: UploadStatus
  platformVideoId: string | null
  platformUrl: string | null
  title: string
  description: string | null
  tags: string[]
  errorMessage: string | null
  publishedAt: string | null
  createdAt: string
}

export interface VideoListFilter {
  platform?: Platform
  status?: UploadStatus
  startDate?: string
  endDate?: string
  keyword?: string
}

export interface VideoCreateRequest {
  title: string
  description?: string
  tags?: string[]
  category?: string
  thumbnailUrl?: string
  visibility?: Visibility
  mediaType?: MediaType
}

export interface VideoPublishRequest {
  platforms: PlatformPublishConfig[]
  scheduledAt?: string
}

export interface PlatformPublishConfig {
  platform: Platform
  title: string
  description: string
  tags: string[]
  visibility: Visibility
}

export interface UploadProgress {
  bytesUploaded: number
  bytesTotal: number
  percentage: number
  speed: number
  remainingSeconds: number
}

export type OptimizationSeverity = 'GOOD' | 'WARNING' | 'ERROR'

export interface OptimizationSuggestion {
  field: string
  severity: OptimizationSeverity
  message: string
  currentValue: string | null
  recommendedValue: string | null
}

export interface OptimizationResult {
  platform: Platform
  score: number
  suggestions: OptimizationSuggestion[]
}

export interface OptimizationCheckRequest {
  title: string
  description?: string
  tags?: string[]
  thumbnailUrl?: string
  platforms?: Platform[]
}

export interface OptimizationCheckResponse {
  results: OptimizationResult[]
}

// Video Processing Upgrade Types

export interface VideoMediaInfo {
  id: number
  videoId: number
  videoCodec: string | null
  width: number | null
  height: number | null
  fps: number | null
  bitrateKbps: number | null
  durationMs: number | null
  colorSpace: string | null
  pixelFormat: string | null
  profile: string | null
  audioCodec: string | null
  audioBitrateKbps: number | null
  sampleRate: number | null
  audioChannels: number | null
  formatName: string | null
  fileSizeBytes: number | null
  createdAt: string
}

export interface VideoSubtitle {
  id: number
  videoId: number
  language: string
  format: string
  content: string
  isAutoGenerated: boolean
  createdAt: string
  updatedAt: string
}

export type ProcessingStage = 'PROBE' | 'THUMBNAIL' | 'CAPTION' | 'UPLOAD'

export interface VideoProcessingProgress {
  id: number
  videoId: number
  stage: ProcessingStage
  platform: Platform | null
  progressPercent: number
  message: string | null
  createdAt: string
  updatedAt: string
}

export interface ThumbnailResult {
  thumbnails: string[]
  selectedIndex: number
}

export interface VideoResize {
  id: number
  originalVideoId: number
  aspectRatio: string
  width: number
  height: number
  fileUrl: string | null
  status: string
  createdAt: string | null
}

export interface VideoTranslation {
  id: number
  videoId: number
  language: string
  title?: string
  description?: string
  tags: string[]
  subtitleContent?: string
  status: string
  createdAt?: string
}
