-- V14: Add new platform types for SNS/Blog/Video platform integrations
ALTER TYPE platform_type ADD VALUE IF NOT EXISTS 'TWITTER';
ALTER TYPE platform_type ADD VALUE IF NOT EXISTS 'FACEBOOK';
ALTER TYPE platform_type ADD VALUE IF NOT EXISTS 'THREADS';
ALTER TYPE platform_type ADD VALUE IF NOT EXISTS 'PINTEREST';
ALTER TYPE platform_type ADD VALUE IF NOT EXISTS 'LINKEDIN';
ALTER TYPE platform_type ADD VALUE IF NOT EXISTS 'WORDPRESS';
ALTER TYPE platform_type ADD VALUE IF NOT EXISTS 'TUMBLR';
ALTER TYPE platform_type ADD VALUE IF NOT EXISTS 'VIMEO';
ALTER TYPE platform_type ADD VALUE IF NOT EXISTS 'DAILYMOTION';
