package com.ongo.common.enums

enum class AiFeature(
    val displayName: String,
    val creditCost: Int,
) {
    META_GENERATION("제목/설명 생성", 5),
    HASHTAG_RECOMMENDATION("해시태그 추천", 3),
    STT("영상 STT 변환", 10),
    SCRIPT_ANALYSIS("스크립트 분석", 5),
    COMMENT_REPLY("댓글 답변 생성", 2),
    SCHEDULE_SUGGESTION("업로드 시간 추천", 3),
    CONTENT_IDEA("콘텐츠 아이디어", 5),
    PERFORMANCE_REPORT("성과 리포트", 8),
    WEEKLY_DIGEST("주간 다이제스트", 8),
    CONTENT_GAP_ANALYSIS("콘텐츠 갭 분석", 10),
    COMPETITOR_INSIGHT("경쟁자 벤치마킹 인사이트", 8),
    SENTIMENT_ANALYSIS("감정 분석", 0),
    STRATEGY_COACH("AI 전략 코치", 10),
    REVENUE_REPORT("수익 분석 리포트", 8),
    FAQ_CLUSTERING("FAQ 자동 분류", 5),
    BATCH_REPLY_DRAFT("배치 답변 초안", 3),
    CONTENT_CALENDAR("AI 콘텐츠 캘린더", 8),
    REVENUE_FORECAST("AI 수익 예측", 10),
    REVENUE_INSIGHT("수익 인사이트 생성", 5),
    META_REWRITE("메타데이터 리라이트", 3),
    CONTENT_REPURPOSE("콘텐츠 리퍼포징", 10),
    CHANNEL_AUDIT("채널 오디트", 15),
    KEYWORD_RESEARCH("키워드 리서치", 3),
    VIDEO_SEO_SCORE("비디오 SEO 점수", 2),
    VIEWS_PREDICTION("조회수 예측", 3),
    PUBLISH_CHECKLIST("게시 전 체크리스트", 2),
    ENGAGEMENT_BENCHMARK("참여율 벤치마크", 3),
}
