package com.ongo.common.enums

enum class Permission {
    // Video
    VIDEO_CREATE, VIDEO_READ, VIDEO_UPDATE, VIDEO_DELETE, VIDEO_PUBLISH,
    // Schedule
    SCHEDULE_CREATE, SCHEDULE_READ, SCHEDULE_UPDATE, SCHEDULE_DELETE,
    // Analytics
    ANALYTICS_READ, ANALYTICS_EXPORT,
    // AI
    AI_USE, AI_BATCH,
    // Team
    TEAM_MANAGE, TEAM_INVITE, TEAM_REMOVE,
    // Approval
    APPROVAL_CREATE, APPROVAL_APPROVE, APPROVAL_REJECT,
    // Settings
    SETTINGS_READ, SETTINGS_UPDATE,
    // Billing
    BILLING_READ, BILLING_MANAGE,
    // Automation
    AUTOMATION_CREATE, AUTOMATION_UPDATE, AUTOMATION_DELETE,
    // UGC Campaign
    CAMPAIGN_VIEW, CAMPAIGN_MANAGE, CAMPAIGN_REVIEW, CAMPAIGN_REWARD_MANAGE,
    // UGC 쇼츠 파이프라인 (프롬프트·템플릿 관리)
    SHORTS_PIPELINE_VIEW, SHORTS_PIPELINE_MANAGE,
}
