package com.ongo.domain.accountdeletion

/**
 * `users` 를 참조하는 모든 외래키의 계정 삭제 정책.
 *
 * 이 레지스트리가 **삭제 권한의 유일한 출처**다. `pg_constraint` 는 참조 관계와 삭제 순서를
 * 알려줄 뿐 "이 행을 지워도 되는가"는 알려주지 않는다. 메타데이터만 보고 자동 삭제하면
 * 새 기능이 정책 검토를 우회하는 fail-open 이 된다.
 *
 * 근거와 판정 과정은 `docs/plans/account-deletion-policy-table.md` 에 있다.
 *
 * 항목을 늘리거나 정책을 올릴 때는 그 문서의 근거부터 갱신한다.
 * 분류되지 않은 외래키가 하나라도 생기면 `AccountDeletionPolicyGuardIT` 가 실패한다.
 *
 * ## 근거는 소유성이어야 한다
 *
 * "지금 `@Profile("wip")` 이라 행이 없다"는 **정책 근거가 아니다.** 그건 현재 상태일 뿐이고
 * 기능이 켜지면 사라진다. 각 항목의 `rationale` 은 누가 그 행을 소유하는지로 적는다.
 *
 * ## wip 해제 시 재검토
 *
 * 아래 두 테이블은 컨트롤러가 `@Profile("wip")` 이라 지금은 행이 생기지 않는다.
 * `DELETE` 로 둔 근거는 소유성이지만, **기능이 wip 을 벗을 때 실제 쓰기 경로를 보고
 * 정책을 다시 확인한다.** 그때 공유·외부 리소스가 붙었을 수 있다.
 * - `ai_content_calendars`
 * - `channel_health_metrics`
 */
object UserFkPolicyRegistry {

    val entries: List<UserFkPolicy> = listOf(
        entry("ab_tests_user_id_fkey", "ab_tests", "user_id", FkPolicy.DELETE, RowOperation.ROW_DELETE,
            "개인 실험. 자식 ab_test_variants 는 CASCADE. 스케줄러 경로만 있다"),
        entry("api_keys_user_id_fkey", "api_keys", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "개인 API 키지만 외부 자동화 클라이언트의 접근을 먼저 폐기하는 삭제 절차가 미완성이다. 판단 전까지 차단한다"),
        entry("academy_enrollments_user_id_fkey", "academy_enrollments", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("activity_logs_user_id_fkey", "activity_logs", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("agency_creators_user_id_fkey", "agency_creators", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("agency_workspaces_owner_user_id_fkey", "agency_workspaces", "owner_user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("ai_content_calendars_user_id_fkey", "ai_content_calendars", "user_id", FkPolicy.DELETE, RowOperation.ROW_DELETE,
            "사용자 단독 소유인 개인 캘린더. user_id 단일 참조이고 다른 사용자가 걸리지 않는다. 자식 외래키 없음"),
        entry("ai_credits_user_id_fkey", "ai_credits", "user_id", FkPolicy.DELETE, RowOperation.ROW_DELETE,
            "사용자별 현재 AI 잔액 상태. 구매·사용 이력은 별도 보존 정책으로 분리하고 잔액 row 자체는 삭제한다"),
        entry("ai_pipeline_jobs_user_id_fkey", "ai_pipeline_jobs", "user_id", FkPolicy.DELETE, RowOperation.ROW_DELETE,
            "AI 파이프라인 상태·결과는 사용자 단독 작업 데이터이며 계정 삭제 시 함께 제거한다"),
        entry("ai_batch_jobs_user_id_fkey", "ai_batch_jobs", "user_id", FkPolicy.DELETE, RowOperation.ROW_DELETE,
            "AI 배치 상태·결과는 사용자 단독 작업 데이터이며 계정 삭제 시 함께 제거한다"),
        entry("ai_credit_transactions_user_id_fkey", "ai_credit_transactions", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("ai_purchased_credits_user_id_fkey", "ai_purchased_credits", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("approval_chains_approver_id_fkey", "approval_chains", "approver_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("approval_comments_user_id_fkey", "approval_comments", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("approvals_requester_id_fkey", "approvals", "requester_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("approvals_reviewer_id_fkey", "approvals", "reviewer_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("approvals_user_id_fkey", "approvals", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("assets_user_id_fkey", "assets", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("audience_profiles_user_id_fkey", "audience_profiles", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("audience_segments_user_id_fkey", "audience_segments", "user_id", FkPolicy.DELETE, RowOperation.ROW_DELETE,
            "개인 세그먼트 정의. 자식 audience_profile_segments 는 CASCADE"),
        entry("automation_rules_user_id_fkey", "automation_rules", "user_id", FkPolicy.DELETE, RowOperation.ROW_DELETE,
            "개인 자동화 설정. 자식 automation_logs 는 CASCADE"),
        entry("automation_workflows_user_id_fkey", "automation_workflows", "user_id", FkPolicy.DELETE, RowOperation.ROW_DELETE,
            "개인 워크플로. 자식 actions/conditions/executions 전부 CASCADE"),
        entry("board_activities_user_id_fkey", "board_activities", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("board_tasks_assignee_id_fkey", "board_tasks", "assignee_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("brand_deals_user_id_fkey", "brand_deals", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("brand_kits_user_id_fkey", "brand_kits", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("brand_mentions_user_id_fkey", "brand_mentions", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("brands_user_id_fkey", "brands", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("brand_schedule_items_user_id_fkey", "brand_schedule_items", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("brand_voice_profiles_user_id_fkey", "brand_voice_profiles", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("campaign_segments_user_id_fkey", "campaign_segments", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("channel_audit_reports_user_id_fkey", "channel_audit_reports", "user_id", FkPolicy.DELETE, RowOperation.ROW_DELETE,
            "개인 리포트. 자식 FK 없음"),
        entry("channel_health_metrics_user_id_fkey", "channel_health_metrics", "user_id", FkPolicy.DELETE, RowOperation.ROW_DELETE,
            "사용자 단독 소유인 개인 채널 지표. user_id 단일 참조이고 자식 health_trends 는 CASCADE 라 함께 정리된다"),
        entry("channels_user_id_fkey", "channels", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("collab_requests_user_id_fkey", "collab_requests", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("comment_faq_templates_user_id_fkey", "comment_faq_templates", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("comments_user_id_fkey", "comments", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("commerce_platforms_user_id_fkey", "commerce_platforms", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("commerce_products_user_id_fkey", "commerce_products", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("competitor_profiles_user_id_fkey", "competitor_profiles", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("competitor_reports_user_id_fkey", "competitor_reports", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("competitors_user_id_fkey", "competitors", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("content_ab_tests_user_id_fkey", "content_ab_tests", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("content_clips_user_id_fkey", "content_clips", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("content_rewrite_results_user_id_fkey", "content_rewrite_results", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("content_rights_user_id_fkey", "content_rights", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("content_series_user_id_fkey", "content_series", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("copyright_check_results_user_id_fkey", "copyright_check_results", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("coupon_usages_user_id_fkey", "coupon_usages", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("creator_portfolios_user_id_fkey", "creator_portfolios", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("creator_profiles_user_id_fkey", "creator_profiles", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("cross_platform_reports_user_id_fkey", "cross_platform_reports", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("drive_import_jobs_user_id_fkey", "drive_import_jobs", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("fan_activities_user_id_fkey", "fan_activities", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("fan_campaigns_user_id_fkey", "fan_campaigns", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("fan_polls_user_id_fkey", "fan_polls", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("fan_rewards_user_id_fkey", "fan_rewards", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("funding_goals_user_id_fkey", "funding_goals", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("funding_transactions_user_id_fkey", "funding_transactions", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("funnel_comparisons_user_id_fkey", "funnel_comparisons", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("funnel_stages_user_id_fkey", "funnel_stages", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("goals_user_id_fkey", "goals", "user_id", FkPolicy.DELETE, RowOperation.ROW_DELETE,
            "개인 목표. 자식 goal_milestones 는 CASCADE"),
        entry("growth_goals_user_id_fkey", "growth_goals", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("hashtag_sets_user_id_fkey", "hashtag_sets", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("ideas_user_id_fkey", "ideas", "user_id", FkPolicy.DELETE, RowOperation.ROW_DELETE,
            "단독 소유 확인 — 공개/공유 컬럼 0개, REFERENCES ideas 인 FK 0건, 컨트롤러가 전부 본인 CRUD. reference_url 은 사용자가 입력한 외부 링크지 우리 스토리지가 아니다"),
        entry("inbox_messages_user_id_fkey", "inbox_messages", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("influencer_profiles_user_id_fkey", "influencer_profiles", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("keyword_alerts_user_id_fkey", "keyword_alerts", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("keyword_research_history_user_id_fkey", "keyword_research_history", "user_id", FkPolicy.DELETE, RowOperation.ROW_DELETE,
            "개인 검색 이력. keyword 는 외부 식별자가 아니다"),
        entry("library_folders_user_id_fkey", "library_folders", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("library_items_user_id_fkey", "library_items", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("link_bio_pages_user_id_fkey", "link_bio_pages", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("live_alert_configs_user_id_fkey", "live_alert_configs", "user_id", FkPolicy.DELETE, RowOperation.ROW_DELETE,
            "개인 알림 설정. 자식 FK 없음"),
        entry("live_dashboard_alerts_user_id_fkey", "live_dashboard_alerts", "user_id", FkPolicy.DELETE, RowOperation.ROW_DELETE,
            "개인 알림 이력. 자식 FK 없음"),
        entry("live_streams_user_id_fkey", "live_streams", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("marketplace_listings_user_id_fkey", "marketplace_listings", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("marketplace_orders_buyer_id_fkey", "marketplace_orders", "buyer_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("marketplace_orders_seller_id_fkey", "marketplace_orders", "seller_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("media_kits_user_id_fkey", "media_kits", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("music_recommendations_user_id_fkey", "music_recommendations", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("notifications_user_id_fkey", "notifications", "user_id", FkPolicy.DELETE, RowOperation.ROW_DELETE,
            "개인 알림과 읽음 상태. 외부 식별자나 공유 주체가 없는 사용자 단독 데이터"),
        entry("optimal_slots_user_id_fkey", "optimal_slots", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("payments_user_id_fkey", "payments", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("performance_predictions_user_id_fkey", "performance_predictions", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("performance_reports_user_id_fkey", "performance_reports", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("playlists_user_id_fkey", "playlists", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("portfolios_user_id_fkey", "portfolios", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("public_api_posts_user_id_fkey", "public_api_posts", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "외부 API 게시 이력과 예약 상태의 보존·취소 정책이 미완성이다. 판단 전까지 삭제를 차단한다"),
        entry("public_oauth_apps_owner_id_fkey", "public_oauth_apps", "owner_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "사용자 소유 개발자 앱은 외부 클라이언트의 접근 폐기와 함께 처리해야 한다. 앱 폐기 절차가 미완성이다"),
        entry("public_oauth_authorization_codes_user_id_fkey", "public_oauth_authorization_codes", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "외부 OAuth 승인 코드의 만료·감사 보존 정책이 미완성이다. 판단 전까지 삭제를 차단한다"),
        entry("public_oauth_tokens_user_id_fkey", "public_oauth_tokens", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "외부 OAuth 토큰의 전량 폐기와 클라이언트 영향 검증 절차가 미완성이다. 판단 전까지 삭제를 차단한다"),
        entry("quality_reports_user_id_fkey", "quality_reports", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("recurring_schedules_user_id_fkey", "recurring_schedules", "user_id", FkPolicy.DELETE, RowOperation.ROW_DELETE,
            "개인 반복 일정. 자식 FK 없음"),
        entry("recycling_suggestions_user_id_fkey", "recycling_suggestions", "user_id", FkPolicy.DELETE, RowOperation.ROW_DELETE,
            "개인 추천 결과. 자식 FK 없음"),
        entry("refresh_tokens_user_id_fkey", "refresh_tokens", "user_id", FkPolicy.DELETE, RowOperation.ROW_DELETE,
            "인증 세션 토큰. 계정 삭제 시 즉시 폐기해야 하며 보존할 이유가 없다"),
        entry("repurpose_jobs_user_id_fkey", "repurpose_jobs", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("resize_jobs_user_id_fkey", "resize_jobs", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("revenue_projections_user_id_fkey", "revenue_projections", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("revenue_streams_user_id_fkey", "revenue_streams", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("rights_alerts_user_id_fkey", "rights_alerts", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("schedule_recommendations_user_id_fkey", "schedule_recommendations", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("schedules_user_id_fkey", "schedules", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("scripts_user_id_fkey", "scripts", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("script_templates_user_id_fkey", "script_templates", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("smart_reply_configs_user_id_fkey", "smart_reply_configs", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("smart_reply_rules_user_id_fkey", "smart_reply_rules", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("smart_reply_suggestions_user_id_fkey", "smart_reply_suggestions", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("sponsorships_user_id_fkey", "sponsorships", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("subscriptions_user_id_fkey", "subscriptions", "user_id", FkPolicy.DELETE, RowOperation.ROW_DELETE,
            "무료·무외부식별자 구독 row는 삭제한다. 유료·시험·결제 식별자가 있는 계정은 AuthUseCase의 추가 구독 가드가 차단한다"),
        entry("subtitle_jobs_user_id_fkey", "subtitle_jobs", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("subtitle_tracks_user_id_fkey", "subtitle_tracks", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("team_members_user_id_fkey", "team_members", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("templates_user_id_fkey", "templates", "user_id", FkPolicy.DELETE, RowOperation.ROW_DELETE,
            "개인 템플릿. 자식 FK 없음"),
        entry("translation_glossary_user_id_fkey", "translation_glossary", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("translation_jobs_user_id_fkey", "translation_jobs", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("trend_alerts_user_id_fkey", "trend_alerts", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("trend_predictions_user_id_fkey", "trend_predictions", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("usage_alert_configs_user_id_fkey", "usage_alert_configs", "user_id", FkPolicy.DELETE, RowOperation.ROW_DELETE,
            "개인 알림 설정. 자식 FK 없음"),
        entry("user_content_sources_user_id_fkey", "user_content_sources", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("user_settings_user_id_fkey", "user_settings", "user_id", FkPolicy.DELETE, RowOperation.ROW_DELETE,
            "사용자 개인 환경설정. 외부 식별자나 공유 주체가 없는 사용자 단독 데이터"),
        entry("videos_user_id_fkey", "videos", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("video_favorites_user_id_fkey", "video_favorites", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "개인 즐겨찾기지만 원본 영상과의 보존·삭제 순서를 함께 처리하는 절차가 미완성이다. 판단 전까지 차단한다"),
        entry("video_scripts_user_id_fkey", "video_scripts", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("visual_workflows_user_id_fkey", "visual_workflows", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("watermarks_user_id_fkey", "watermarks", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("webhooks_user_id_fkey", "webhooks", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("weekly_digests_user_id_fkey", "weekly_digests", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("weekly_reports_user_id_fkey", "weekly_reports", "user_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
        entry("workflow_executions_user_id_fkey", "workflow_executions", "user_id", FkPolicy.DELETE, RowOperation.ROW_DELETE,
            "위 실행 이력. automation_workflows 의 자식이기도 해 CASCADE 로 함께 사라진다"),
        entry("workspaces_owner_id_fkey", "workspaces", "owner_id", FkPolicy.REVIEW_BLOCK, RowOperation.ROW_BLOCK,
            "정책 미정. 판단 전까지 이 외래키로 엮인 행이 있는 사용자는 삭제하지 않는다"),
    )

    private val byKey: Map<UserFkKey, UserFkPolicy> = entries.associateBy { it.key }

    fun find(key: UserFkKey): UserFkPolicy? = byKey[key]

    /** 삭제 대상 외래키. 순서는 여기서 정하지 않는다 — 메타데이터 그래프가 정한다. */
    fun deletable(): List<UserFkPolicy> = entries.filter { it.policy == FkPolicy.DELETE }

    private fun entry(
        constraintName: String,
        table: String,
        localColumns: String,
        policy: FkPolicy,
        rowOperation: RowOperation,
        rationale: String,
    ) = UserFkPolicy(
        key = UserFkKey(
            schema = "public",
            constraintName = constraintName,
            table = table,
            localColumns = localColumns.split(","),
            referencedColumns = listOf("id"),
        ),
        policy = policy,
        rowOperation = rowOperation,
        rationale = rationale,
    )
}
